export const gematriaMeanings: Record<number, string> = {
  1: "Leadership & Initiative",
  2: "Cooperation & Balance",
  3: "Creativity & Joy",
  4: "Structure & Discipline",
  5: "Freedom & Change",
  6: "Responsibility & Harmony",
  7: "Spirituality & Analysis",
  8: "Power & Abundance",
  9: "Completion & Wisdom",
  11: "Master Intuition & Insight",
  13: "Hidden Transformation",
  14: "Creative Communication",
  16: "Spiritual Awakening",
  17: "Hope and Faith",
  18: "Material Temptation",
  19: "Spiritual Leader",
  22: "Master Builder & Manifestation",
  26: "Divine Power",
  33: "Master Healer & Compassion",
  37: "Creative Expression",
  43: "Creative Transformation",
  44: "Material Mastery",
  47: "Intuitive Structure",
  54: "Dynamic Expression",
  64: "Spiritual Work",
  72: "Divine Harmony",
  74: "Rebel Spirit",
  77: "Spiritual Warrior",
  88: "Material Abundance",
  93: "Universal Compassion",
  99: "Cosmic Completion",
  108: "Sacred Totality",
  111: "Manifesting Thought",
  144: "Chosen Path",
  369: "Universal Keys",
  416: "Spiritual Expansion",
};

export const gematriaColorMap: Record<number, string> = {
  1: 'text-red-500',
  2: 'text-green-500',
  3: 'text-pink-500',
  4: 'text-blue-500',
  5: 'text-yellow-500',
  6: 'text-emerald-500',
  7: 'text-indigo-400',
  8: 'text-orange-500',
  9: 'text-gray-500',
  11: 'text-purple-500',
  13: 'text-indigo-500',
  14: 'text-teal-400',
  16: 'text-purple-400',
  17: 'text-blue-400',
  18: 'text-rose-400',
  19: 'text-lime-400',
  22: 'text-purple-500',
  26: 'text-pink-600',
  33: 'text-purple-500',
  37: 'text-amber-400',
  43: 'text-cyan-400',
  44: 'text-blue-600',
  47: 'text-indigo-400',
  54: 'text-pink-400',
  64: 'text-emerald-400',
  72: 'text-green-500',
  74: 'text-red-400',
  77: 'text-indigo-400',
  88: 'text-orange-500',
  93: 'text-teal-400',
  99: 'text-indigo-500',
  108: 'text-fuchsia-500',
  111: 'text-yellow-400',
  144: 'text-purple-400',
  369: 'text-fuchsia-600',
  416: 'text-fuchsia-500',
};

export const getGematriaWords = (value: number) => {
  const wordMap: Record<number, string[]> = {
    157: ['Spiritual Being'],
    26: ['God', 'Divine Power'],
    74: ['Lucifer', 'Rebel Spirit'],
    144: ['Chosen', 'Divine Structure'],
    33: ['Divine Code', 'Master Healer'],
    108: ['Sacred Totality', 'Completion'],
    416: ['Spiritual Expansion'],
    54: ['Dynamic Change', 'Versatile Expression'],
    369: ['Universal Keys', 'Tesla Energy'],
    88: ['Wealth', 'Infinity'],
    72: ['Divine Balance', 'Spiritual Wisdom'],
  };
  return wordMap[value] || [];
};
  
export function getGematriaDescription(num: number): string {
  const descriptions: Record<number, string> = {
    1: 'Unity, beginnings, leadership.',
    2: 'Balance, duality, diplomacy.',
    3: 'Creativity, joy, expansion.',
    4: 'Stability, logic, work.',
    5: 'Freedom, change, adventure.',
    6: 'Responsibility, care, harmony.',
    7: 'Mystery, knowledge, depth.',
    8: 'Power, material success.',
    9: 'Completion, humanity, service.',
    11: 'Divine intuition and enlightenment.',
    13: 'Transformation and rebirth.',
    14: 'Communication and magnetism.',
    16: 'Karmic cleansing, spiritual awakening.',
    17: 'Hope, faith, and prosperity.',
    18: 'Materialism, tests of strength.',
    19: 'Success through service.',
    22: 'Mastery of the physical world.',
    26: 'Balance of material and spiritual.',
    33: 'Master Healer, universal compassion.',
    37: 'Creativity and originality.',
    43: 'Creative transformation and evolution.',
    44: 'Power and physical achievement.',
    47: 'Spiritual intuition and knowledge.',
    54: 'Dynamic expression and energy.',
    64: 'Spiritual work and discipline.',
    72: 'Balance through wisdom.',
    74: 'Rebellion against limitations.',
    77: 'Spiritual mastery and warrior spirit.',
    88: 'Abundance and infinite potential.',
    93: 'Universal compassion and love.',
    99: 'Endings and cosmic wisdom.',
    108: 'Sacred spiritual wholeness.',
    111: 'Manifestation of thoughts into reality.',
    144: 'Chosen path, spiritual builders.',
    369: 'Universal code of creation.',
    416: 'Expansion of spiritual consciousness.',
  };
  return descriptions[num] || 'No description available.';
}
